### ISSUE TITLE
Setup website for this repo

### ISSUE THREAD

**Issue by wu-sheng** [SkyAPM/document-cn-translation-of-skywalking#12]
More translations are going to be provided, we will need to set up the website, maybe GitHub page with some theme.

**Comment by kezhenxu94** [comment]
> More translations are going to be provided, we will need to set up the website, maybe GitHub page with some theme.

I'm considering using the same blog template as the official website apache/incubator-skywalking-website (Vuepress), are there any concerns?

**Comment by wu-sheng** [comment]
> I'm considering using the same blog template as the official website apache/incubator-skywalking-website (Vuepress), are there any concerns?

The template is fine, but please make sure the theme, pic is clearly different. From ASF policy, the translation website must be clear that it is not the official Apache website.

**Comment by wu-sheng** [comment]
Do you work on the template in this month? Or we could simply open GitBook or something to host doc site first?

**Comment by wu-sheng** [comment]
I think all documents have been provided by @kezhenxu94 @KAMIJYOUDOUMA @thelight1

As we are going to announce this in DevCon, I hope you three could provide some personal info
- Name(cn)
- Company(if you want)
- Photo(or use GitHub avatar)

Send mail to my apache mail, wusheng@apache.org

Then I will ask the speaker to show you all on a separated slide.

**Comment by wu-sheng** [comment]
@kezhenxu94 What do you prefer for the website?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 What do you prefer for the website?

Hi @wu-sheng sorry for the late response, I'm still finding a solution to support versioning docs, I've found [one](https://github.com/koumoul-dev/gh-pages-multi) but I haven't got time to give it a try (am a little busy at other stuff recently :-)

Since all the docs are provided as Chinese language now, for better reading experience, I agree with you to provide simple GitHub pages or GitBook for now and put the versioning solution a little bit later.

If it's ok, the GitHub pages may need a title, I think it's impossible to use SkyWalking because of branding issue. What's your suggestion?

**Comment by wu-sheng** [comment]
> If it's ok, the GitHub pages may need a title, I think it's impossible to use SkyWalking because of branding issue. What's your suggestion?

How about `SkyWalking文档社区翻译版`?

For version, how about we provide a link list at index page, such as
- 6.0.0-GA, links to `/6.0.0-GA/...`

**Comment by wu-sheng** [comment]
FYI @hanahmily You are the speaker of new project release, which should include this too. Could you add this to your slides?

**Comment by kezhenxu94** [comment]
> > If it's ok, the GitHub pages may need a title, I think it's impossible to use SkyWalking because of branding issue. What's your suggestion?
> 
> How about `SkyWalking文档社区翻译版`?

I'm thinking whether it's possible to put some other materials in this site except for the documentations, such as blogs, source-code analysis article, user cases sharing etc. in Chinese (we have lots of Chinese users), if it's possible, how about `SkyWalking 中文社区` ?

> 
> For version, how about we provide a link list at index page, such as
> 
> * 6.0.0-GA, links to `/6.0.0-GA/...`

at this moment, I think it the best solution, I'll try to set up before this weekend (hopefully)

**Comment by wu-sheng** [comment]
> I'm thinking whether it's possible to put some other materials in this site except for the documentations, such as blogs, source-code analysis article, user cases sharing etc. in Chinese (we have lots of Chinese users), if it's possible, how about SkyWalking 中文社区 ?

Chinese blogs have been supported to host here, http://skywalking.apache.org/zh/blog/ . If the translator team is stable and have more than 5 volunteers, I would expect even to move this into Apache(with core contributors as committers). What do you think?

> at this moment, I think it the best solution, I'll try to set up before this weekend (hopefully)

Thanks. Please change this repo structure too. We don't include the version in the path right now.

**Comment by kezhenxu94** [comment]
> Chinese blogs have been supported to host here, http://skywalking.apache.org/zh/blog/ . If the translator team is stable and have more than 5 volunteers, I would expect even to move this into Apache(with core contributors as committers). What do you think?

It would be better to hold the materials all together there, but it's far from the standard to move into Apache, so leave it, so I'll use `SkyWalking 文档社区翻译版` as suggested.

> Thanks. Please change this repo structure too. We don't include the version in the path right now.

Yes I will.

**Comment by wu-sheng** [comment]
> It would be better to hold the materials all together there, but it's far from the standard to move into Apache, so leave it as, so I'll use SkyWalking 文档社区翻译版 as suggested.

Yes, I have concerns to out-of-date again, as the project develops so quickly by a lot of contributors.

**Comment by wu-sheng** [comment]
It is working now. https://skyapm.github.io/document-cn-translation-of-skywalking/ I will change the repo website url
