### ISSUE TITLE
Miss root doc

### ISSUE THREAD

**Issue by wu-sheng** [SkyAPM/document-cn-translation-of-skywalking#18]
Look like we miss this, https://github.com/apache/skywalking/tree/master/docs :)

**Comment by kezhenxu94** [comment]
@wu-sheng got it, will sync this later



> Posted from [mini-github](https://github.com/kezhenxu94/mini-github)
发送自微信小程序 [GitHub 专业版](https://github.com/kezhenxu94/mini-github)
