### ISSUE TITLE
SkyWalking 6.1 document update

### ISSUE THREAD

**Issue by wu-sheng** [SkyAPM/document-cn-translation-of-skywalking#22]
According to the log, we only have one for document udpate
- https://github.com/apache/skywalking/pull/2566

But in my memory, should be more, I think we need to tag the pr more accurately in 6.2

We have to scan all PRs in 6.1, https://github.com/apache/skywalking/milestone/32?closed=1

**Comment by kezhenxu94** [comment]
HI @wu-sheng , I did not scan all the PRS in 6.1, instead, I just scan all the commits of `docs` folder after the time when translation is done, hope I did not miss anything.
