### ISSUE TITLE
How to help with the translation?

### ISSUE THREAD

**Issue by KAMIJYOUDOUMA** [SkyAPM/document-cn-translation-of-skywalking#3]
I'd like to help with the translation,what can I do for this?

**Comment by wu-sheng** [comment]
@kezhenxu94 I think you could lead here.

**Comment by kezhenxu94** [comment]
> I'd like to help with the translation,what can I do for this?

@KAMIJYOUDOUMA Thanks for your interest in this, you can help with the translation in the following step:

- [fork this repo](https://github.com/SkyAPM/document-cn-translation-of-skywalking/fork) and [clone it to your local machine](https://help.github.com/en/articles/cloning-a-repository)
- synchronize the un-translated documentation files from [the English version](https://github.com/apache/incubator-skywalking/tree/master/docs/en), please carefully keep the hierachy of the files and folders
- do the translation work, please keep terminology consistent through the whole documentation (you can refer to the translated files and feel free to correct it if needed)
- commit and push the translated files to the repo you forked in first step
- [open a pull request](https://github.com/SkyAPM/document-cn-translation-of-skywalking/compare?expand=1)

if you have any trouble, please feel free to ask for help here, @wu-sheng and I are very glad to help.

Thanks again for your attention.

**Comment by kezhenxu94** [comment]
@KAMIJYOUDOUMA and please open an issue to address that which file(s) you'd like to translate or which files you are working on, we need this in case that other contributors are translating the same file(s), thus avoid duplicated work. Thanks :)

**Comment by KAMIJYOUDOUMA** [comment]
> @KAMIJYOUDOUMA and please open an issue to address that which file(s) you'd like to translate or which files you are working on, we need this in case that other contributors are translating the same file(s), thus avoid duplicated work. Thanks :)

I'd like like to translate the flies in directory [FAQ](https://github.com/apache/incubator-skywalking/tree/master/docs/en/FAQ),is there any problems?@kezhenxu94

**Comment by kezhenxu94** [comment]
> > @KAMIJYOUDOUMA and please open an issue to address that which file(s) you'd like to translate or which files you are working on, we need this in case that other contributors are translating the same file(s), thus avoid duplicated work. Thanks :)
> 
> I'd like like to translate the flies in directory [FAQ](https://github.com/apache/incubator-skywalking/tree/master/docs/en/FAQ),is there any problems?@kezhenxu94

No problem, there is no one working on this, go ahead. Thanks

**Comment by kezhenxu94** [comment]
> ok, I want to translate the files in directory [protocols](https://github.com/apache/incubator-skywalking/tree/master/docs/en/protocols)

Hi @thelight1 , the files under directory protocols have been almostly translated (only 2 files left, I'll commit them tonight :) I suggest you to translate files under directory [setup](https://github.com/apache/incubator-skywalking/tree/master/docs/en/setup), you can translate parts of them, and please open an issue to address it, if you prefer files under `protocol`, please only translate the following files (others have been translated but not committed), thanks

```
Trace-Data-Protocol-v1.md
Trace-Data-Protocol-v2.md
```

**Comment by thelight1** [comment]
> > ok, I want to translate the files in directory [protocols](https://github.com/apache/incubator-skywalking/tree/master/docs/en/protocols)
> 
> Hi @thelight1 , the files under directory protocols have been almostly translated (only 2 files left, I'll commit them tonight :) I suggest you to translate files under directory [setup](https://github.com/apache/incubator-skywalking/tree/master/docs/en/setup), you can translate parts of them, and please open an issue to address it, if you prefer files under `protocol`, please only translate the following files (others have been translated but not committed), thanks
> 
> ```
> Trace-Data-Protocol-v1.md
> Trace-Data-Protocol-v2.md
> ```

ok，I will translate some files under directory [setup](https://github.com/apache/incubator-skywalking/tree/master/docs/en/setup). I'll translate the files under [setup/service-agent/java-agent](https://github.com/apache/incubator-skywalking/tree/master/docs/en/setup/service-agent/java-agent) first，then some files under [setup/backend](https://github.com/apache/incubator-skywalking/tree/master/docs/en/setup/backend). I want to understand how Skywalking works by this.

**Comment by kezhenxu94** [comment]
>  I want to understand how Skywalking works by this.

That's really a good practice to understand SkyWalking by translating the documentations, I'm looking forward to your pull request :) thanks

**Comment by kezhenxu94** [comment]
Hi all, I've seperated the translation tasks and created issues for them, new contributors please comment under those issues (like something **I want to take this task**) to let others know that the task is taken.

**Comment by wu-sheng** [comment]
FYI @KAMIJYOUDOUMA @thelight1 @kezhenxu94 We are going to have an even, DevCon Shanghai, on May 11th, if we have chance to announce the Chinese documents have been provided by the community, would be great news.

Although we know, keeping it updated is another challenge we will face.

 Thank you all contributions to the project. If this could catch the time, please let me known.

**Comment by wu-sheng** [comment]
@KAMIJYOUDOUMA @kezhenxu94 I am sending the invitation of joining `SkyAPM`/`
cn-document-team`.

@thelight1 After your PR merged, if you want to join, just ping me.

**Comment by kezhenxu94** [comment]
> FYI @KAMIJYOUDOUMA @thelight1 @kezhenxu94 We are going to have an even, DevCon Shanghai, on May 11th, if we have chance to announce the Chinese documents have been provided by the community, would be great news.
> 
> Although we know, keeping it updated is another challenge we will face.
> 
> Thank you all contributions to the project. If this could catch the time, please let me known.

Hi @wu-sheng , I've just summarized the progress of the translation work:

[x] `setup/backend` is taken by @thelight1 and is under review #6 
[x] `setup/envoy` is taken by I myself and is under review #7 
[ ] `setup/istio` is taken by I myself and is under translation
[x] `setup/service-agent` is taken by @KAMIJYOUDOUMA and is under review #13 (though only part of them)
[x] all of the other files are translated
[ ] the website (GH pages) is to be built, (this may not be a must before announcing the news)

and it seems that the progress is promising, I believe it is possible to announce that the Chinese version of the doc is available at that time, thanks again @KAMIJYOUDOUMA @thelight1 

> Although we know, keeping it updated is another challenge we will face.

Please ping me and the other maintainers if the English version is changed in any commit/PR

**Comment by wu-sheng** [comment]
@kezhenxu94 How about we create one issue for each SkyWalking release version? Then we could link PRs including document change to it. As a result, we could have a list to cross check.

**Comment by wu-sheng** [comment]
> the website (GH pages) is to be built, (this may not be a must before announcing the news)

I think this is totally optional.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 How about we create one issue for each SkyWalking release version? Then we could link PRs including document change to it. As a result, we could have a list to cross check.

That's a good idea

**Comment by wu-sheng** [comment]
We create new one instead of this?

**Comment by kezhenxu94** [comment]
> We create new one instead of this?

I think it's time to create a new one to track the changes afterward as you metioned in https://github.com/SkyAPM/document-cn-translation-of-skywalking/issues/3#issuecomment-483717740
