### ISSUE TITLE
[咨询] 为什么中文文档单独一个仓库

### ISSUE THREAD

**Issue by shalk** [SkyAPM/document-cn-translation-of-skywalking#41]
想问一下， 为什么中文文档没有放在skywalking的repo里。

另外，一点建议，是否考虑把文档都放在website里，直接通过浏览器可以访问到

例如 
https://github.com/apache/dubbo-website/tree/master/docs
http://dubbo.apache.org/zh-cn/docs/admin/ops/skywalking.html

**Comment by zitongchen** [comment]
现在的中文文档由社区维护，所以没有放到 skywalking 的 repo 里面；在此项目的 README 中有相应版本的在线文档链接，可以在线浏览（虽然在线文档没有目录）。

**Comment by wu-sheng** [comment]
> 另外，一点建议，是否考虑把文档都放在website里，直接通过浏览器可以访问到

目前没有有效的技术手段，保证website库，可以分版本发布。因为项目每个版本文档有比较明显的差异。
