### ISSUE TITLE
[注意] Window 系统下 SkyWalking 放置在含有空格的目录里面快速启动会闪退（启动失败）

### ISSUE THREAD

**Issue by zitongchen** [SkyAPM/document-cn-translation-of-skywalking#42]
是否可以考虑在《Backend和UI部署》章节的快速入门中提醒一下用户不能把 SkyWalking 放置在 Window 系统含有**空格**的目录里面(例如：**D:\Program Files**），否则快速启动会闪退。

**Comment by SataQiu** [comment]
感谢！如果确实存在问题，建议先去修改英文原版，提个 PR，待审核通过合并后，再更新中文版

**Comment by Tidhy** [comment]
过来踩个坑🥺
