### ISSUE TITLE
dashboard怎么配置下用户名和密码

### ISSUE THREAD

**Issue by liuhonglin** [SkyAPM/document-cn-translation-of-skywalking#46]
浏览器输入地址就直接进去了，没有强制登录，怎么配置必须登录才能看

**Comment by kezhenxu94** [comment]
登陆功能不在 APM 系统的核心功能范围内, 核心开发团队没有时间精力去开发, 且社区没有贡献者贡献此功能, 登陆功能需要用户自己实现
