### ISSUE TITLE
[Translation Task] setup / backend

### ISSUE THREAD

**Issue by kezhenxu94** [SkyAPM/document-cn-translation-of-skywalking#6]
Files: [setup/backend](https://github.com/apache/incubator-skywalking/tree/master/docs/en/setup/backend)

**Comment by KAMIJYOUDOUMA** [comment]
I'd like to do it.

**Comment by kezhenxu94** [comment]
> I'd like to do it.

Thanks, task is taken by @KAMIJYOUDOUMA

**Comment by kezhenxu94** [comment]
HI @KAMIJYOUDOUMA , what's the status of this task? You can create a pull request (even it includes only part of your works) and get reviewed by others 😄

**Comment by KAMIJYOUDOUMA** [comment]
> HI @KAMIJYOUDOUMA , what's the status of this task? You can create a pull request (even it includes only part of your works) and get reviewed by others 😄

I created a pull request,but only part of my works.I will complete it today.
