### ISSUE TITLE
中文文档更新

### ISSUE THREAD

**Issue by Superskyyy** [SkyAPM/document-cn-translation-of-skywalking#60]
I aim to give a major update to the current CN translation doc, in alignment with the upcoming release - ~~[v8.5.0](https://github.com/apache/skywalking/releases/tag/v8.5.0)~~ -> [v8.6.0](https://github.com/apache/skywalking/releases/tag/v8.6.0)

我会把当前的 SkyWalking 中文文档校对并更新至 ~~[v8.5.0](https://github.com/apache/skywalking/releases/tag/v8.5.0)~~ -> [v8.6.0](https://github.com/apache/skywalking/releases/tag/v8.6.0) 版本，将来会跟随版本发行更新中文文档。

FYI, 这个 Issue 用来记录翻新进程，避免社区出现重复劳动。

- [ ] 校对已有部分
- [ ] 更新至 v8.6.0 @3854eed

**Comment by Superskyyy** [comment]
@wu-sheng May I get the write access to this repo? I'd like to do some experiments and put in my partially translated work.

**Comment by kezhenxu94** [comment]
> @wu-sheng May I get the write access to this repo? I'd like to do some experiments and put in my partially translated work.

Invite is sent. Please check you email inbox.

**Comment by Superskyyy** [comment]
> > @wu-sheng May I get the write access to this repo? I'd like to do some experiments and put in my partially translated work.
> 
> Invite is sent. Please check you email inbox.

Got it, planning to try a translation platform free for open-source projects, incremental translation for small chunks of text can be achieved + public access for people to participate.

**Comment by Superskyyy** [comment]
https://www.transifex.com/test-1377/showcase-3/translate/#zh/readmemd/340666084 try see this, login via github and should be good to go.

**Comment by wu-sheng** [comment]
@Superskyyy I am planning to archive this repo, I think you should have the same feeling from your experience, for a super active community, to maintain a en->cn sync docs requires a lot of ppl and time, I think we don't have such a group people

**Comment by Superskyyy** [comment]
> @Superskyyy I am planning to archive this repo, I think you should have the same feeling from your experience, for a super active community, to maintain a en->cn sync docs requires a lot of ppl and time, I think we don't have such a group people

Yes I can certainly feel it, maintaining a up to date sync is very hard (I observe the large mismatches in other communities that do support CN docs too). 

Anyway in the end, there is a https://developers.google.com/season-of-docs event that we could pay attention to next year.
