### ISSUE TITLE
[Translation Task] setup / service-agent

### ISSUE THREAD

**Issue by kezhenxu94** [SkyAPM/document-cn-translation-of-skywalking#9]
Files under directory [setup/service-agent/java-agent](https://github.com/apache/incubator-skywalking/tree/master/docs/en/setup/service-agent/java-agent)

**Comment by kezhenxu94** [comment]
Taken by @thelight1

**Comment by kezhenxu94** [comment]
HI @thelight1 , what's the status of this task? You can create a pull request (even it includes only part of your works) and get reviewed by others

**Comment by thelight1** [comment]
I have translated some files about setup and created a pull request。
I know little about how Skywalking works，so I don't understand the meaning of  Agent Configuration Properties exactly。When review the pull request, please pay more attention to the translation of Agent Configuration Properties。

**Comment by kezhenxu94** [comment]
> I have translated some files about setup and created a pull request。
> I know little about how Skywalking works，so I don't understand the meaning of Agent Configuration Properties exactly。When review the pull request, please pay more attention to the translation of Agent Configuration Properties。

@thelight1 when you finish please ping me, thanks :)

**Comment by thelight1** [comment]
@kezhenxu94 The translation of the files under [setup/service-agent/java-agent](https://github.com/apache/incubator-skywalking/tree/master/docs/en/setup/service-agent/java-agent) has been finished. :)
